INSERT INTO company VALUES
  (DEFAULT, 'NTNU');

INSERT INTO campus VALUES
  (DEFAULT, 'Gløshaugen', 1),
  (DEFAULT, 'Dragvoll', 1),
  (DEFAULT, 'Kalvskinnet', 1),
  (DEFAULT, 'Øya', 1),
  (DEFAULT, 'Tyholt', 1),
  (DEFAULT, 'Moholt', 1),
  (DEFAULT, 'Ålesund', 1),
  (DEFAULT, 'Gjøvik', 1),
  (DEFAULT, 'Tunga', 1),
  (DEFAULT, 'Valgrinda', 1),
  (DEFAULT, 'Olavskvartalet', 1),
  (DEFAULT, 'Solsiden', 1),
  (DEFAULT, 'Heggdalen', 1),
  (DEFAULT, 'Brattøra', 1);

INSERT INTO building VALUES
  (DEFAULT, '1902-bygget', 4),
  (DEFAULT, '1930-bygget', 4),
  (DEFAULT, 'Akrinn', 3),
  (DEFAULT, 'Akutt/hjerte/lungesenteret', 4),
  (DEFAULT, 'Ametyst', 8),
  (DEFAULT, 'Arkitekt Christies gate 2', 3),
  (DEFAULT, 'Berg', 1),
  (DEFAULT, 'Beryll', 8),
  (DEFAULT, 'Bevegelsessenteret', 4),
  (DEFAULT, 'Biologisk stasjon', 13),
  (DEFAULT, 'Brattørkaia 17B', 14),
  (DEFAULT, 'Byggteknisk', 1),
  (DEFAULT, 'Dragvoll Bygg 1 - 6', 2),
  (DEFAULT, 'Dragvoll Bygg 11 - 12', 2),
  (DEFAULT, 'Dragvoll Bygg 7 - 10', 2),
  (DEFAULT, 'Dragvoll gård', 2),
  (DEFAULT, 'Driftsentralen', 1),
  (DEFAULT, 'Elektro A', 1),
  (DEFAULT, 'Elektro B', 1),
  (DEFAULT, 'Elektro C', 1),
  (DEFAULT, 'Elektro D', 1),
  (DEFAULT, 'Elektro E/F', 1),
  (DEFAULT, 'Elgesetergt 10', 4),
  (DEFAULT, 'Elvegata 17 (Fylkesmannsboligen)', 3),
  (DEFAULT, 'Fagskolen', 7),
  (DEFAULT, 'Fjordgata 1', 11),
  (DEFAULT, 'Forsyningssenteret', 4),
  (DEFAULT, 'Gamle elektro', 1),
  (DEFAULT, 'Gamle fysikk', 1),
  (DEFAULT, 'Gamle kjemi', 1),
  (DEFAULT, 'Gastrosenteret', 4),
  (DEFAULT, 'Geologi', 1),
  (DEFAULT, 'Gjøvik gård', 8),
  (DEFAULT, 'Gjøvik International School', 8),
  (DEFAULT, 'Gløshaugen legesenter', 1),
  (DEFAULT, 'Gneis', 8),
  (DEFAULT, 'Grønnbygget', 1),
  (DEFAULT, 'Gunnerus gate 1', 3),
  (DEFAULT, 'Gunnerusbiblioteket', 3),
  (DEFAULT, 'Gunnerushuset', 3),
  (DEFAULT, 'Handelshøyskolen', 1),
  (DEFAULT, 'Havlaboratoriet', 5),
  (DEFAULT, 'Helvin', 8),
  (DEFAULT, 'Hovedbygget', 1),
  (DEFAULT, 'Hovedbygget', 7),
  (DEFAULT, 'Høgskoleringen 3', 1),
  (DEFAULT, 'Idrettsbygget', 1),
  (DEFAULT, 'Idrettssenteret', 2),
  (DEFAULT, 'Industribygget', 12),
  (DEFAULT, 'Infohuset', 1),
  (DEFAULT, 'IT-bygget, sydfløy', 1),
  (DEFAULT, 'IT-bygget, vestfløy', 1),
  (DEFAULT, 'Jonsvannsveien 82', 6),
  (DEFAULT, 'K-bygget', 7),
  (DEFAULT, 'Kavitasjonslaboratoriet', 5),
  (DEFAULT, 'Kjelhuset', 1),
  (DEFAULT, 'Kjemi 1', 1),
  (DEFAULT, 'Kjemi 2', 1),
  (DEFAULT, 'Kjemi 3', 1),
  (DEFAULT, 'Kjemi 4', 1),
  (DEFAULT, 'Kjemi 5', 1),
  (DEFAULT, 'Kjemi sydfløy', 1),
  (DEFAULT, 'Kjemihall', 1),
  (DEFAULT, 'Kjøpmannsgata 42', 11),
  (DEFAULT, 'Klostergata 46', 4),
  (DEFAULT, 'Kobolt', 8),
  (DEFAULT, 'Krambugt 12/14', 11),
  (DEFAULT, 'Kunnskapssenteret', 4),
  (DEFAULT, 'Kvinne-barnsenteret', 4),
  (DEFAULT, 'Lab-bygg', 7),
  (DEFAULT, 'Laboratoriesenteret', 4),
  (DEFAULT, 'Lerchendal gård', 10),
  (DEFAULT, 'Lysholm-bygget', 3),
  (DEFAULT, 'Låven', 2),
  (DEFAULT, 'Marinteknisk senter', 5),
  (DEFAULT, 'Materialteknisk', 1),
  (DEFAULT, 'Metallurgi', 1),
  (DEFAULT, 'MTFS', 4),
  (DEFAULT, 'Mustad bygn. 109', 8),
  (DEFAULT, 'Mustad bygn, 114', 8),
  (DEFAULT, 'NHL', 10),
  (DEFAULT, 'NMK Nautikk', 7),
  (DEFAULT, 'Nevrosenteret', 4),
  (DEFAULT, 'Olavskvartalet', 11),
  (DEFAULT, 'Oppredning/gruvedrift', 1),
  (DEFAULT, 'Paviljong A', 2),
  (DEFAULT, 'Paviljong B', 2),
  (DEFAULT, 'Paviljong C', 2),
  (DEFAULT, 'Petroleumsteknisk senter', 10),
  (DEFAULT, 'PFI', 1),
  (DEFAULT, 'Plantebiosenteret', 2),
  (DEFAULT, 'Produktdesign', 1),
  (DEFAULT, 'PTS hallbygg', 10),
  (DEFAULT, 'PTS paviljong', 10),
  (DEFAULT, 'Realfagbygget', 1),
  (DEFAULT, 'Retorten', 3),
  (DEFAULT, 'Schøninghuset', 3),
  (DEFAULT, 'Samfunnsforskning', 2),
  (DEFAULT, 'Sentralbygg 1', 1),
  (DEFAULT, 'Sentralbygg 2', 1),
  (DEFAULT, 'Skiboli', 10),
  (DEFAULT, 'Skipsmodelltanken', 5),
  (DEFAULT, 'Sluppenvegen 14', 10),
  (DEFAULT, 'Smaragd', 8),
  (DEFAULT, 'StatPed', 8),
  (DEFAULT, 'Statsarkivet', 1),
  (DEFAULT, 'Strømningsteknisk', 1),
  (DEFAULT, 'Studentboligen (Det ensomme fengsel)', 3),
  (DEFAULT, 'Suhmhuset', 3),
  (DEFAULT, 'Sukkerhuset', 3),
  (DEFAULT, 'Sverres gate 10', 3),
  (DEFAULT, 'Sverres gate 14', 3),
  (DEFAULT, 'Sverres gate 15', 3),
  (DEFAULT, 'Transportsentralen', 10),
  (DEFAULT, 'Trondheim Spektrum', 4),
  (DEFAULT, 'Tungasletta 2', 9),
  (DEFAULT, 'Tungavegen 32', 9),
  (DEFAULT, 'Tunglab', 5),
  (DEFAULT, 'Turbinlaboratoriet', 10),
  (DEFAULT, 'Utleirahallen', 2),
  (DEFAULT, 'Valgrinda 2000', 10),
  (DEFAULT, 'Vannkraftlaboratoriet', 1),
  (DEFAULT, 'Varmeteknisk', 1),
  (DEFAULT, 'Vassbygget', 10),
  (DEFAULT, 'Verkstedteknisk', 1),
  (DEFAULT, 'Vestre Gløshaugen', 1),
  (DEFAULT, 'VM-paviljongen', 1),
  (DEFAULT, 'Østre Gløshaugen', 1),
  (DEFAULT, 'Øya helsehus', 4);

INSERT INTO floor VALUES
  (DEFAULT, '5', 95),
  (DEFAULT, '4', 95),
  (DEFAULT, '3', 95),
  (DEFAULT, '2', 95),
  (DEFAULT, '1', 95),
  (DEFAULT, 'U1', 95),
  (DEFAULT, 'U2', 95),
  (DEFAULT, 'U3', 95),
  (DEFAULT, 'U4', 95),
  (DEFAULT, '14', 100),
  (DEFAULT, '13', 100),
  (DEFAULT, '12', 100),
  (DEFAULT, '11', 100),
  (DEFAULT, '10', 100),
  (DEFAULT, '9', 100),
  (DEFAULT, '8', 100),
  (DEFAULT, '7', 100),
  (DEFAULT, '6', 100),
  (DEFAULT, '5', 100),
  (DEFAULT, '4', 100),
  (DEFAULT, '3', 100),
  (DEFAULT, '2', 100),
  (DEFAULT, '1', 100),
  (DEFAULT, 'K', 100),
  (DEFAULT, '13', 99),
  (DEFAULT, '12', 99),
  (DEFAULT, '11', 99),
  (DEFAULT, '10', 99),
  (DEFAULT, '9', 99),
  (DEFAULT, '8', 99),
  (DEFAULT, '7', 99),
  (DEFAULT, '6', 99),
  (DEFAULT, '5', 99),
  (DEFAULT, '4', 99),
  (DEFAULT, '3', 99),
  (DEFAULT, '2', 99),
  (DEFAULT, '1', 99),
  (DEFAULT, 'K', 99),
  (DEFAULT, '6', 3),
  (DEFAULT, '5', 3),
  (DEFAULT, '4', 3),
  (DEFAULT, '3', 3),
  (DEFAULT, '2', 3),
  (DEFAULT, '1', 3),
  (DEFAULT, 'U1', 3),
  (DEFAULT, 'U2', 3);

INSERT INTO room VALUES
  (DEFAULT, 'R1', 6),
  (DEFAULT, 'R2', 6),
  (DEFAULT, 'R3', 6),
  (DEFAULT, 'R4', 6),
  (DEFAULT, 'R5', 6),
  (DEFAULT, 'R6', 6),
  (DEFAULT, 'R7', 6),
  (DEFAULT, 'R8', 6),
  (DEFAULT, 'R9', 6),
  (DEFAULT, 'R10', 1),
  (DEFAULT, 'S1', 38),
  (DEFAULT, 'S2', 38),
  (DEFAULT, 'S3', 38),
  (DEFAULT, 'S4', 38),
  (DEFAULT, 'S5', 38),
  (DEFAULT, 'S6', 24),
  (DEFAULT, 'S7', 24),
  (DEFAULT, 'S8', 24),
  (DEFAULT, 'A001', 46);

INSERT INTO item_type VALUES
  ('Nøkkel', 'Key'),
  ('Nøkkelknippe', 'Keychain'),
  ('Paraply', 'Umbrella'),
  ('Jakke', 'Jacket'),
  ('Genser', 'Sweater'),
  ('Bok', 'Book'),
  ('Kalkulator', 'Calculator'),
  ('Laptoplader', 'Laptop charger'),
  ('Mobillader', 'Phone charger'),
  ('Mobiltelefon', 'Mobile phone'),
  ('Laptop', 'Laptop');