INSERT INTO company VALUES
  (DEFAULT, 'NTNU');

INSERT INTO campus VALUES
  (DEFAULT, 'Gløshaugen', 1),
  (DEFAULT, 'Dragvoll', 1),
  (DEFAULT, 'Kalvskinnet', 1),
  (DEFAULT, 'Øya', 1),
  (DEFAULT, 'Tyholt', 1),
  (DEFAULT, 'Moholt', 1),
  (DEFAULT, 'Ålesund', 1),
  (DEFAULT, 'Gjøvik', 1),
  (DEFAULT, 'Tunga', 1),
  (DEFAULT, 'Valgrinda', 1),
  (DEFAULT, 'Olavskvartalet', 1),
  (DEFAULT, 'Solsiden', 1),
  (DEFAULT, 'Heggdalen', 1);

INSERT INTO building VALUES
  (DEFAULT, '1902-bygget', 4),
  (DEFAULT, 'Akrinn (Sverres gate 12/Teknologibygget)', 3),
  (DEFAULT, 'Akutt/hjerte/lungesenteret', 4),
  (DEFAULT, 'Ametyst', 8),
  (DEFAULT, 'Arkitekt Christies gate 2', 3),
  (DEFAULT, 'Berg', 1),
  (DEFAULT, 'Beryll', 8),
  (DEFAULT, 'Bevegelsessenteret', 4),
  (DEFAULT, 'Biologisk stasjon', 13),
  (DEFAULT, 'Byggteknisk', 1),
  (DEFAULT, 'Dragvoll Bygg 1 - 6', 2),
  (DEFAULT, 'Dragvoll Bygg 11 - 12', 2),
  (DEFAULT, 'Dragvoll Bygg 7 - 10', 2),
  (DEFAULT, 'Elektro A', 1),
  (DEFAULT, 'Elektro B', 1),
  (DEFAULT, 'Elektro E/F', 1),
  (DEFAULT, 'Fagskolen', 7),
  (DEFAULT, 'Fjordgata 1', 11),
  (DEFAULT, 'Gamle elektro', 1),
  (DEFAULT, 'Gamle fysikk', 1),
  (DEFAULT, 'Gamle kjemi', 1),
  (DEFAULT, 'Gastrosenteret', 4),
  (DEFAULT, 'Geologi', 1),
  (DEFAULT, 'Gjøvik gård', 8),
  (DEFAULT, 'Gneis', 8),
  (DEFAULT, 'Grønnbygget', 1),
  (DEFAULT, 'Gunnerus gate 1', 3),
  (DEFAULT, 'Gunnerusbiblioteket', 3),
  (DEFAULT, 'Gunnerushuset', 3),
  (DEFAULT, 'Handelshøyskolen', 1),
  (DEFAULT, 'Helvin', 8),
  (DEFAULT, 'Hovedbygget', 1),
  (DEFAULT, 'Hovedbygget', 7),
  (DEFAULT, 'Høgskoleringen 3', 1),
  (DEFAULT, 'IT-bygget, sydfløy', 1),
  (DEFAULT, 'Idrettssenteret', 2),
  (DEFAULT, 'Industribygget', 12),
  (DEFAULT, 'Jonsvannsveien 82', 6),
  (DEFAULT, 'Kjelhuset', 1),
  (DEFAULT, 'Kjemi 1', 1),
  (DEFAULT, 'Kjemi 2', 1),
  (DEFAULT, 'Kjemi 3', 1),
  (DEFAULT, 'Kjemi 4', 1),
  (DEFAULT, 'Kjemi 5', 1),
  (DEFAULT, 'Kjøpmannsgata 42', 11),
  (DEFAULT, 'Klostergata 46', 4),
  (DEFAULT, 'Kobolt', 8),
  (DEFAULT, 'Krambugt 12/14', 11),
  (DEFAULT, 'Kunnskapssenteret', 4),
  (DEFAULT, 'Kvinne-barnsenteret', 4),
  (DEFAULT, 'Lab-bygg', 7),
  (DEFAULT, 'Laboratoriesenteret', 4),
  (DEFAULT, 'Lysholm-bygget (Lærerkvartalet)', 3),
  (DEFAULT, 'Låven', 2),
  (DEFAULT, 'MTFS', 4),
  (DEFAULT, 'Marinteknisk senter', 5),
  (DEFAULT, 'Marinteknisk senter - tunglab', 5),
  (DEFAULT, 'Mustad bygn. 109', 8),
  (DEFAULT, 'NHL Hall utvidelse', 10),
  (DEFAULT, 'NMK Nautikk', 7),
  (DEFAULT, 'Nevrosenteret', 4),
  (DEFAULT, 'Olavskvartalet', 11),
  (DEFAULT, 'Oppredning/gruvedrift', 1),
  (DEFAULT, 'PTS Paviljong', 10),
  (DEFAULT, 'Petroleumsteknisk senter', 10),
  (DEFAULT, 'Realfagbygget', 1),
  (DEFAULT, 'Retorten', 3),
  (DEFAULT, 'Sentralbygg 1', 1),
  (DEFAULT, 'Sentralbygg 2', 1),
  (DEFAULT, 'Sluppenvegen 14', 10),
  (DEFAULT, 'Smaragd', 8),
  (DEFAULT, 'StatPed', 8),
  (DEFAULT, 'Suhmhuset', 3),
  (DEFAULT, 'Sukkerhuset', 3),
  (DEFAULT, 'Sverres gate 10', 3),
  (DEFAULT, 'Tungasletta 2', 9),
  (DEFAULT, 'Tungavegen 32 Bygg 1', 9),
  (DEFAULT, 'Valgrinda 2000', 10),
  (DEFAULT, 'Varmeteknisk', 1),
  (DEFAULT, 'Vassbygget', 10),
  (DEFAULT, 'Verkstedteknisk', 1),
  (DEFAULT, 'Øya helsehus', 4);