name:                api
version:             0.1.0.0
github:              "fishyfrogface/mistan"
license:             BSD3
author:              "Camilla Rygh"
copyright:           "Camilla Rygh (c) 2019"
category:            Web

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fishyfrogface/mistan#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - servant-server
  - wai
  - warp
  - postgresql-simple

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
    - api
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson